//
// Created by Dima Zapolsky on 13.07.2020.
//

#ifndef NAIVEINTERPRETER_SRC_NODES_DECLARATION_DECLARATIONSINCLUDE_H_
#define NAIVEINTERPRETER_SRC_NODES_DECLARATION_DECLARATIONSINCLUDE_H_

#include "ClassDeclaration.h"
#include "MethodDeclaration.h"
#include "VariableDeclaration.h"

#endif //NAIVEINTERPRETER_SRC_NODES_DECLARATION_DECLARATIONSINCLUDE_H_
